name: qt-static build
 
on:
  push:
    branches: [ master ]

# NOTE: stuff inside ${{}} gets evaluated by the GitHub Actions system before anything else
# see the docs for "context" in GitHub Actions
jobs:
  win_vcpkg_test_nightly_release_build:
    name: "qt-static build"
    runs-on: windows-2019
      
    steps:
    # checkout the repo to the default working dir. repo files will be immediately at top-level in the default working dir.
    # so, for example the path to README.md is just .\README.md and not .\qBittorrent\README.md
    - name: checkout repo
      uses: actions/checkout@v2

   # Cache/Restore the vcpkg's build artifacts.
    - name: Cache artifacts
      uses: actions/cache@v1
      with:
        path: C:\Qt
        # The key will be different each time a different version of vcpkg is used, or different ports are installed.
        key: qtbase-14.1

     
    - name: enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.1.0
      with:
        arch: amd64
        spectre: true
       
    - name: download strawberryperl
      shell: cmd
      run: |
        tools\gnuwin32\bin\curl -L -C - -O http://strawberryperl.com/download/5.30.2.1/strawberry-perl-5.30.2.1-64bit-portable.zip
        tools\gnuwin32\bin\curl x -aos -y -oC:\Strawberry strawberry-perl-5.30.2.1-64bit-portable.zip
    
    - name: download python
      shell: cmd
      run: |
        tools\gnuwin32\bin\curl -L -C - -O https://www.python.org/ftp/python/3.7.7/python-3.7.7-embed-amd64.zip
        tools\gnuwin32\bin\curl x -aos -y -oC:\Python python-3.7.7-embed-amd64.zip
        
    - name: downloading files
      shell: cmd
      run: |
        qt download
    
    - name: building openssl
      shell: cmd
      run: | 
        qt openssl
        
    - name: building qt
      shell: cmd
      run: |
        qt setup
        qt build
        
    # ...and upload zip with artifcats
    - name: "upload artifact as zip"
      uses: actions/upload-artifact@v1
      with:
        name: qtbase_builds
        path: C:\Qt
